### ISSUE TITLE
cosin_add_m_layer.cpp的疑问

### ISSUE THREAD

**Issue by math-yyj** [xialuxi/arcface-caffe#1]
看起来没发现loss的计算部分，损失函数层并没有出现在这些文件里？

**Comment by mathyyj** [comment]
还是说先做cosin_add_m处理之后，再传到普通的softmax层损失？

**Comment by xialuxi** [comment]
cosin_add_m处理之后，再传到普通的softmax层损失.
这里不涉及损失函数，只是变换，和求梯度。

**Comment by zhaowwenzhong** [comment]
老师，有实验例子吗？lfw
