### ISSUE TITLE
关键点检测网络问题

### ISSUE THREAD

**Issue by echofeng** [xialuxi/arcface-caffe#20]
关键点检测的网络用的是可分离卷积，权重大小应该是filter_sizexfliter_sizexoutput_channel，
但实际上权重大小却是为input_channelxfilter_sizexfliter_sizexoutput_channel，类似普通的卷积。
我把这些可分离卷积改成了正常卷积，测试程序可运行，但结果不对，麻烦确认下。

**Comment by xialuxi** [comment]
这个确实有问题，训练的时候忘了加group参数，导致权重的通道数不是为1，暂时使用deepwise结构不加group参数来测试吧。
