### ISSUE TITLE
landmark 检测不准

### ISSUE THREAD

**Issue by LilioISnotAfox** [xialuxi/arcface-caffe#27]
你好，我尝试了两个模型的关键点检测，出来的效果都不准。后来尝试加了人脸框检测，并未有所改善，请问是什么地方我忽略了吗？

**Comment by xialuxi** [comment]
请问你使用的是什么人脸检测算法？

**Comment by LilioISnotAfox** [comment]
旷视的API

**Comment by LilioISnotAfox** [comment]
使用您的mtcnn检测出来的landmark也不准

**Comment by xialuxi** [comment]
能否把你的图片画上检测狂，贴出来看下？

**Comment by LilioISnotAfox** [comment]
![1 (3)](https://user-images.githubusercontent.com/37403574/58004551-0f6fe880-7b16-11e9-9e64-66cb828023ce.jpg)
![3 (3)](https://user-images.githubusercontent.com/37403574/58004553-10087f00-7b16-11e9-9c72-482ebe52f615.jpg)

**Comment by xialuxi** [comment]
建议更换检测算法，你的人脸框偏向于dlib的结果，而模型使用的是ssd的算法跑出来的，两个算法给的框差别很大。

**Comment by LilioISnotAfox** [comment]
请问检测得到的人脸框应该直接输入网络还是画在图片上输入？

**Comment by xialuxi** [comment]
截出来人脸，做关键点检测。

**Comment by LilioISnotAfox** [comment]
好的，非常感谢您的解答！
