### ISSUE TITLE
cosin_add_m_layer的gpu实现？？？

### ISSUE THREAD

**Issue by xiaosuzhang** [xialuxi/arcface-caffe#3]
您好，您有没有写cosin_add_m_layer.cu 文件呢？loss层的cpu计算和gpu计算对网络训练时间影响大吗？

**Comment by xialuxi** [comment]
最近忙，没有写，后期会写。
只是loss层的话，其实还好。

**Comment by sunjunlishi** [comment]
写好了吗，现在用的呀？
