### ISSUE TITLE
我使用softmax损失，10177个id, 20万张图片，loss从开始50左右，训练10个epoch后下降到19左右就在一直震荡，请问你们训练时这么大的数据集loss能下降到多少？而且准确率也不会提升。

### ISSUE THREAD

**Issue by Dian-Yi** [xialuxi/arcface-caffe#38]

**Comment by xisi789** [comment]
> _No description provided._

你解决这个问题吗，我也遇到类似的了

**Comment by Dian-Yi** [comment]
> > _No description provided._
> 
> 你解决这个问题吗，我也遇到类似的了

你数据集规模是多大的？我当前20万的人脸已经能训正常，不过400万的脸的不正常

**Comment by xisi789** [comment]
十万的ID和六百万的人脸

**Comment by Dian-Yi** [comment]
> 十万的ID和六百万的人脸

看来脸多了得要预训练模型慢慢调调，我没用预训练模型，训到一半每个类求得cosin角度都是接近与1，也不知道不知道什么原因造成得？

**Comment by Dian-Yi** [comment]
> 十万的ID和六百万的人脸

你用得什么数据集？这么大？

**Comment by xisi789** [comment]
几个数据集拼在一起的，能调什么呢，我调学习率已经没啥用了

**Comment by Dian-Yi** [comment]
> 几个数据集拼在一起的，能调什么呢，我调学习率已经没啥用了

m和scale,加个imagenet得预训练模型再试试

**Comment by xisi789** [comment]
我调小调大m训练情况更差了
