### ISSUE TITLE
编译Combined Margin Loss 出错？？？

### ISSUE THREAD

**Issue by xiaosuzhang** [xialuxi/arcface-caffe#4]
您好，我刚刚下载了您的最新的Combined Margin Loss文件，但是在编译的时候报错了，您看是什么问题呢？

Severity	Code	Description	Project	File	Line	Suppression State
Error	C2065	'arccos_x': undeclared identifier	libcaffe	E:\AMSoftmax-master\Caffe-AM-Softmax\caffe-windows\src\caffe\layers\combined_margin_layer.cpp	32	
Severity	Code	Description	Project	File	Line	Suppression State
Error	C2228	left of '.mutable_cpu_data' must have class/struct/union	libcaffe	E:\AMSoftmax-master\Caffe-AM-Softmax\caffe-windows\src\caffe\layers\combined_margin_layer.cpp	32	

谢谢您！！

**Comment by xialuxi** [comment]
换成m1_arccos_x_add_m2就好了，谢谢提醒，明天我把编译通过的代码更新上来！
